name: Deploy Test on AWS EC2
on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Grant Gradle
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew bootJar -x test

      # log into docker
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/test:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/test:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker stop test || true
            docker rm test || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/test:latest || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/test:latest
            docker run -d -p 80:8080 \
              -e URL=jdbc:mysql://${{ secrets.RDS_URL }}/user9 \
              -e USERNAME=${{ secrets.RDS_USERNAME }} \
              -e PASSWORD=${{ secrets.RDS_PASSWORD }} \
              --name test \
              ${{ secrets.DOCKER_USERNAME }}/test:latest